BWNguyenVu/swd392-be

- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
Fix flower list is empty when request empty category list
> [UBRO32BIT][REL045][Fix]: Fix flower list is empty when request empty category list

- main-service/src/main/java/com/example/myflower/controller/FlowerCategoryController.java
- main-service/src/main/java/com/example/myflower/dto/auth/requests/CreateFlowerListingRequestDTO.java
- main-service/src/main/java/com/example/myflower/dto/flowercategogy/request/CreateFlowerCategoryRequestDTO.java
- main-service/src/main/java/com/example/myflower/dto/flowercategogy/request/UpdateFlowerCategoryRequestDTO.java
- main-service/src/main/java/com/example/myflower/dto/flowercategogy/response/FlowerCategoryResponseDTO.java
- main-service/src/main/java/com/example/myflower/entity/FlowerCategory.java
- main-service/src/main/java/com/example/myflower/mapper/FlowerCategoryMapper.java
- main-service/src/main/java/com/example/myflower/service/StorageService.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerCategoryServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/StorageServiceImpl.java
Add image field in flower category
> [UBRO32BIT][REL047][Enhance]: Add image field in flower category

- main-service/src/main/java/com/example/myflower/controller/FlowerCategoryController.java
- main-service/src/main/java/com/example/myflower/controller/FlowerListingController.java
- main-service/src/main/java/com/example/myflower/dto/cart/responses/CartItemResponseDTO.java
- main-service/src/main/java/com/example/myflower/repository/FlowerListingRepository.java
- main-service/src/main/java/com/example/myflower/service/FlowerListingService.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
> [UBRO32BIT][REL051][Implement]: Get flower by user ID

- main-service/src/main/java/com/example/myflower/service/impl/StorageServiceImpl.java
File removal when throw exception
> [UBRO32BIT][HotFix]: File removal when throw exception

- main-service/src/main/java/com/example/myflower/dto/auth/requests/UpdateFlowerListingRequestDTO.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerCategoryServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
> [UBRO32BIT][HotFix]: Amazon S3 related error

- main-service/src/main/java/com/example/myflower/dto/auth/requests/CreateFlowerListingRequestDTO.java
- main-service/src/main/java/com/example/myflower/dto/auth/requests/UpdateFlowerListingRequestDTO.java
- main-service/src/main/java/com/example/myflower/dto/auth/responses/FlowerListingResponseDTO.java
- main-service/src/main/java/com/example/myflower/dto/cart/responses/CartItemResponseDTO.java
- main-service/src/main/java/com/example/myflower/entity/FlowerListing.java
- main-service/src/main/java/com/example/myflower/mapper/FlowerListingMapper.java
- main-service/src/main/java/com/example/myflower/service/impl/CartItemServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
> [UBRO32BIT][HotFix]: Changed flower field name

- main-service/src/main/java/com/example/myflower/config/ScheduleConfig.java
- main-service/src/main/java/com/example/myflower/consts/Constants.java
- main-service/src/main/java/com/example/myflower/controller/FlowerListingController.java
- main-service/src/main/java/com/example/myflower/repository/FlowerListingRepository.java
- main-service/src/main/java/com/example/myflower/service/FlowerListingService.java
- main-service/src/main/java/com/example/myflower/service/RedisCommandService.java
- main-service/src/main/java/com/example/myflower/service/RedisService.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/RedisCommandServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/RedisServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/StorageServiceImpl.java
API and cronjob clear flower cache
> [UBRO32BIT][REL053][Implement]: API and cronjob clear flower cache

- main-service/src/main/java/com/example/myflower/mapper/FlowerListingMapper.java
> [UBRO32BIT][Hotfix]: Address field response

- notification-service/pom.xml
- notification-service/src/main/java/com/swd/notification_service/config/WebSocketConfig.java
- notification-service/src/main/java/com/swd/notification_service/services/SocketService.java
- notification-service/src/main/java/com/swd/notification_service/services/impl/NotificationServiceImpl.java
- notification-service/src/main/java/com/swd/notification_service/services/impl/SocketServiceImpl.java
Receive notification via websocket
> [UBRO32BIT][REL039][Implement]: Receive notification via websocket

- main-service/src/main/java/com/example/myflower/controller/FeedbackController.java
- main-service/src/main/java/com/example/myflower/dto/feedback/request/CreateFeedbackRequestDTO.java
- main-service/src/main/java/com/example/myflower/dto/feedback/request/UpdateFeedbackRequestDTO.java
- main-service/src/main/java/com/example/myflower/dto/feedback/response/FeedbackResponseDTO.java
- main-service/src/main/java/com/example/myflower/dto/file/FileResponseDTO.java
- main-service/src/main/java/com/example/myflower/entity/Account.java
- main-service/src/main/java/com/example/myflower/entity/Feedback.java
- main-service/src/main/java/com/example/myflower/entity/FlowerImage.java
- main-service/src/main/java/com/example/myflower/entity/enumType/RatingEnum.java
- main-service/src/main/java/com/example/myflower/exception/ErrorCode.java
- main-service/src/main/java/com/example/myflower/exception/GlobalExceptionHandler.java
- main-service/src/main/java/com/example/myflower/exception/feedback/FeedbackAppException.java
- main-service/src/main/java/com/example/myflower/mapper/FeedbackMapper.java
- main-service/src/main/java/com/example/myflower/repository/FeedbackRepository.java
- main-service/src/main/java/com/example/myflower/service/FeedbackService.java
- main-service/src/main/java/com/example/myflower/service/impl/FeedbackServiceImpl.java
> [UBRO32BIT][REL061][Implement]: Flower feedback

- main-service/src/main/java/com/example/myflower/repository/FlowerListingRepository.java
- main-service/src/main/java/com/example/myflower/service/FlowerListingService.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/OrderServiceImpl.java
- notification-service/src/main/java/com/swd/notification_service/consts/Constants.java
- notification-service/src/main/java/com/swd/notification_service/controller/BroadcastNotificationController.java
- notification-service/src/main/java/com/swd/notification_service/controller/NotificationController.java
- notification-service/src/main/java/com/swd/notification_service/dto/broadcast_notification/request/GetBroadcastNotificationListRequestDTO.java
- notification-service/src/main/java/com/swd/notification_service/dto/broadcast_notification/response/BroadcastNotificationResponseDTO.java
- notification-service/src/main/java/com/swd/notification_service/dto/pagination/CursorPaginationRequest.java
- notification-service/src/main/java/com/swd/notification_service/dto/pagination/request/PaginationRequestDTO.java
- notification-service/src/main/java/com/swd/notification_service/dto/pagination/response/PaginationResponseDTO.java
- notification-service/src/main/java/com/swd/notification_service/entity/BroadcastNotification.java
- notification-service/src/main/java/com/swd/notification_service/mapper/BroadcastNotificationMapper.java
- notification-service/src/main/java/com/swd/notification_service/repository/BroadcastNotificationRepository.java
- notification-service/src/main/java/com/swd/notification_service/repository/NotificationRepository.java
- notification-service/src/main/java/com/swd/notification_service/services/BroadcastNotificationService.java
- notification-service/src/main/java/com/swd/notification_service/services/NotificationService.java
- notification-service/src/main/java/com/swd/notification_service/services/impl/BroadcastNotificationServiceImpl.java
- notification-service/src/main/java/com/swd/notification_service/services/impl/NotificationServiceImpl.java
> [UBRO32BIT][REL062][Implement]: Delete and restore operations

- main-service/src/main/java/com/example/myflower/config/FileConfig.java
- main-service/src/main/java/com/example/myflower/dto/file/FileResponseDTO.java
- main-service/src/main/java/com/example/myflower/dto/flowerlisting/FlowerListingCacheDTO.java
- main-service/src/main/java/com/example/myflower/entity/FlowerImage.java
- main-service/src/main/java/com/example/myflower/entity/FlowerListing.java
- main-service/src/main/java/com/example/myflower/exception/ErrorCode.java
- main-service/src/main/java/com/example/myflower/mapper/FeedbackMapper.java
- main-service/src/main/java/com/example/myflower/mapper/FlowerCategoryMapper.java
- main-service/src/main/java/com/example/myflower/mapper/FlowerListingMapper.java
- main-service/src/main/java/com/example/myflower/mapper/MediaFileMapper.java
- main-service/src/main/java/com/example/myflower/service/AccountService.java
- main-service/src/main/java/com/example/myflower/service/FileMediaService.java
- main-service/src/main/java/com/example/myflower/service/FlowerListingService.java
- main-service/src/main/java/com/example/myflower/service/RedisCommandService.java
- main-service/src/main/java/com/example/myflower/service/StorageService.java
- main-service/src/main/java/com/example/myflower/service/impl/AccountServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/CartItemServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/FeedbackServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/FileMediaServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerCategoryServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/OrderServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/RedisCommandServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/StorageServiceImpl.java
- main-service/src/main/java/com/example/myflower/utils/FileUtils.java
> [UBRO32BIT][REL062][Fix]: Fix cache related bug

- main-service/src/main/java/com/example/myflower/service/RedisCommandService.java
- main-service/src/main/java/com/example/myflower/service/impl/FileMediaServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/RedisCommandServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/StorageServiceImpl.java
Fixed lazy load error, added function logging
> [UBRO32BIT][Fix]: Fixed lazy load error, added function logging

- main-service/src/main/java/com/example/myflower/controller/FlowerCategoryController.java
- main-service/src/main/java/com/example/myflower/service/FlowerCategoryService.java
- main-service/src/main/java/com/example/myflower/service/RedisCommandService.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerCategoryServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/RedisCommandServiceImpl.java
> [UBRO32BIT][Fix]: Added clear category cache

- main-service/src/main/java/com/example/myflower/mapper/FlowerListingMapper.java
- notification-service/src/main/java/com/swd/notification_service/controller/BroadcastNotificationController.java
- notification-service/src/main/java/com/swd/notification_service/controller/NotificationController.java
- notification-service/src/main/java/com/swd/notification_service/dto/notifications/NotificationCountResponseDTO.java
- notification-service/src/main/java/com/swd/notification_service/repository/NotificationRepository.java
- notification-service/src/main/java/com/swd/notification_service/services/NotificationService.java
- notification-service/src/main/java/com/swd/notification_service/services/impl/NotificationServiceImpl.java
Fixed flower expire date missing
> [UBRO32BIT][Fix]: Fixed flower expire date missing

- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
Fixed flower status filter on admin and seller
> [UBRO32BIT][Fix]: Fixed flower status filter on admin and seller

- main-service/src/main/java/com/example/myflower/controller/FlowerListingController.java
- main-service/src/main/java/com/example/myflower/exception/ErrorCode.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
Fixed flower status validation
> [UBRO32BIT][Fix]: Fixed flower status validation

- main-service/src/main/java/com/example/myflower/controller/FlowerListingController.java
- main-service/src/main/java/com/example/myflower/dto/auth/requests/GetFlowerListingsRequestDTO.java
- main-service/src/main/java/com/example/myflower/repository/FlowerListingRepository.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
> [UBRO32BIT][Fix]: Added flower price filtering

- main-service/src/main/java/com/example/myflower/dto/auth/requests/CreateFlowerListingRequestDTO.java
- main-service/src/main/java/com/example/myflower/dto/flowercategogy/request/UpdateFlowerCategoryRequestDTO.java
- main-service/src/main/java/com/example/myflower/entity/FlowerListing.java
- main-service/src/main/java/com/example/myflower/exception/ErrorCode.java
- main-service/src/main/java/com/example/myflower/repository/FlowerListingRepository.java
- main-service/src/main/java/com/example/myflower/service/impl/AccountServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/CartItemServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/FeedbackServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerCategoryServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
- main-service/src/main/java/com/example/myflower/service/impl/StorageServiceImpl.java
> [UBRO32BIT][Fix]: Added flower expire date

- main-service/src/main/java/com/example/myflower/dto/auth/requests/UpdateFlowerListingRequestDTO.java
- main-service/src/main/java/com/example/myflower/dto/auth/responses/FlowerListingResponseDTO.java
- main-service/src/main/java/com/example/myflower/dto/flowerlisting/FlowerListingCacheDTO.java
- main-service/src/main/java/com/example/myflower/mapper/FlowerListingMapper.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
> [UBRO32BIT][Fix]: Flower expire date mapping

- main-service/src/main/java/com/example/myflower/dto/auth/requests/CreateFlowerListingRequestDTO.java
- main-service/src/main/java/com/example/myflower/dto/auth/requests/UpdateFlowerListingRequestDTO.java
- main-service/src/main/java/com/example/myflower/dto/flowercategogy/request/CreateFlowerCategoryRequestDTO.java
- main-service/src/main/java/com/example/myflower/dto/flowercategogy/request/UpdateFlowerCategoryRequestDTO.java
- main-service/src/main/java/com/example/myflower/entity/Blog.java
- main-service/src/main/java/com/example/myflower/entity/CartItem.java
- main-service/src/main/java/com/example/myflower/entity/Feedback.java
- main-service/src/main/java/com/example/myflower/entity/FlowerCategory.java
- main-service/src/main/java/com/example/myflower/entity/FlowerListing.java
- main-service/src/main/java/com/example/myflower/entity/MediaFile.java
Add feedback content length validation on request
> [UBRO32BIT][Fix]: Add feedback content length validation on request

- main-service/src/main/java/com/example/myflower/mapper/FlowerListingMapper.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
Map isDeleted attribute on flower response
> [UBRO32BIT][Fix]: Map isDeleted attribute on flower response

- main-service/src/main/java/com/example/myflower/exception/ErrorCode.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
Map flower expire date to entity
> [UBRO32BIT][Fix]: Map flower expire date to entity

- main-service/src/main/java/com/example/myflower/repository/FlowerListingRepository.java
- main-service/src/main/java/com/example/myflower/service/impl/FlowerListingServiceImpl.java
Fixed delete flower image error
> [UBRO32BIT][Fix]: Fixed delete flower image error
